# Public version
application: xparty-umd
version: dev

# Development and testing
#application: xparty-test
#version: dev

# For Python 2.7:
runtime: python27

api_version: 1

inbound_services:
- channel_presence

libraries:
- name: django
  version: "latest"

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /css
  static_dir: client/css
  
- url: /imgs
  static_dir: client/imgs

- url: /js
  static_dir: client/js
  
- url: /custom
  static_dir: client/custom
 
- url: /cron/students_timeout
  script: server/cron/StudentsTimeoutHandler.py
  login: admin
 
- url: .*
  script: server/main.py

threadsafe: false

skip_files:
# File types to ignore
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?.*\.py[co]
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?\..*
# Directories to ignore
- ^(.*/)?\.svn/.*
